library(qtl)
WSC3 <- read.cross("csv", dir="U:/Breeding methodologies/Teaching/Rqtl", "WSC3.csv", estimate.map=FALSE)
summary(WSC3)
plotMissing(WSC3)
par(mfrow=c(1,2), las=1)
plot(ntyped(WSC3), ylab="No. typed markers", main="No. genotypes per individual")
plot(ntyped(WSC3, "mar"), ylab="No. typed individuals", main="No. genotypes by marker")
par(mfrow=c(1,1), las=1)
WSC3 <- subset(WSC3, ind=(ntyped(WSC3) >50))
nt.bymar <- ntyped(WSC3, "mar")
todrop <- names(nt.bymar[nt.bymar <100])
WSC3 <- drop.markers(WSC3, todrop)
cg <- comparegeno(WSC3)
hist(cg[lower.tri(cg)], breaks=seq(0, 1, len=101), xlab="No. matching genotypes")
rug(cg[lower.tri(cg)])
print(dup <- findDupMarkers(WSC3, exact.only=FALSE))
gt <- geno.table(WSC3)
gt[gt$P.value < 0.05/totmar(WSC3),]
todrop <- rownames(gt[gt$P.value < 1e-10,])
WSC3 <- drop.markers(WSC3, todrop)
g <- pull.geno(WSC3)
gfreq <- apply(g, 1, function(a) table(factor(a, levels=1:5)))
gfreq <- t(t(gfreq) / colSums(gfreq))
par(mfrow=c(1,5), las=1)
for(i in 1:5)
  plot(gfreq[i,], ylab="Genotype frequency", main=c("AA", "AB", "BB", "not.BB", "not.AA")[i],
       ylim=c(0,1))
WSC3 <- est.rf(WSC3)
checkAlleles(WSC3, threshold=5)
rf <- pull.rf(WSC3)
lod <- pull.rf(WSC3, what="lod")
par(mfrow=c(1,1), las=1)
plot(as.numeric(rf), as.numeric(lod), xlab="Recombination fraction", ylab="LOD score")
lg <- formLinkageGroups(WSC3, max.rf=0.35, min.lod=6)
table(lg[,2])
lg <- formLinkageGroups(WSC3, max.rf=0.35, min.lod=5) #try differnt max.rf, and min.lod scores
table(lg[,2])
WSC3 <- formLinkageGroups(WSC3, max.rf=0.35, min.lod=5, reorgMarkers=TRUE)
plotRF(WSC3, alternate.chrid = TRUE)
WSC3 <- orderMarkers(WSC3, chr=7) #start with the chr with the least amount of markers
pull.map(WSC3, chr=7)
rip7 <- ripple(WSC3, chr=7, window=7)
summary(rip7)
rip7lik <- ripple(WSC3, chr=7, window=4, method="likelihood", error.prob=0.02)
summary(rip7lik)
compareorder(WSC3, chr=7, c(1:6, 9,8,7,10), error.prob=0.02)
WSC3 <- switch.order(WSC3, chr=7, c(1:6, 9,8,7,10), error.prob=0.02)
pull.map(WSC3, chr=7)
WSC3 <- orderMarkers(WSC3, chr=6)
pull.map(WSC3, chr=6)
rip6 <- ripple(WSC3, chr=6, window=7)
summary(rip6)
rip6lik <-ripple(WSC3, chr=6, window=4, method="likelihood", error.prob=0.02)
summary(rip6lik)
WSC3 <-orderMarkers(WSC3, chr=5)
pull.map(WSC3, chr=5)
rip5 <- ripple(WSC3, chr=5, window=7)
summary(rip5)
rip5lik <- ripple(WSC3, chr=5, window=3, method="likelihood", error.prob=0.02)
summary(rip5lik)
pat5 <- apply(rip5[,1:17], 1, paste, collapse=":")
pat5lik <- apply(rip5lik[,1:17], 1, paste, collapse=":")
rip5 <- rip5[match(pat5lik, pat5),]
plot(rip5[,"obligXO"], rip5lik[,"LOD"], xlab="obligate crossover count chr=5",
     ylab="LOD score")
WSC3 <- orderMarkers(WSC3, chr=4)
pull.map(WSC3, chr=4)
rip4 <- ripple(WSC3, chr=4, window=7)
summary(rip4)
rip4lik <- ripple(WSC3, chr=4, window=3, method="likelihood", error.prob=0.005)
summary(rip4lik)
pull.map(WSC3, chr=4)
WSC3 <- orderMarkers(WSC3, chr=3)
pull.map(WSC3, chr=3)
rip3 <- ripple(WSC3, chr=3, window=7)
summary(rip3)
rip3lik <- ripple(WSC3, chr=3, window=3, method="likelihood", error.prob=0.005)
summary(rip3lik)
WSC3 <- switch.order(WSC3, chr=3, c(1:17, 19,18,20, 21:25), error.prob=0.005)
pull.map(WSC3, chr=3)
WSC3 <- orderMarkers(WSC3, chr=2)
pull.map(WSC3, chr=2)
rip2 <- ripple(WSC3, chr=2, window=7)
summary(rip2)
rip2lik <- ripple(WSC3, chr=2, window=3, method="likelihood", error.prob=0.02)
summary(rip2lik)
WSC3 <- orderMarkers(WSC3, chr=1)
pull.map(WSC3, chr=1)
rip1 <- ripple(WSC3, chr=1, window=7)
summary(rip1)
rip1lik <- ripple(WSC3, chr=1, window=3, method="likelihood", error.prob=0.02)
summary(rip1lik) 
#possibly switch order
#WSC3 <- switch.order(WSC3, chr=1, c(1:28, 30,29, 31:34), error.prob=0.005)
#pull.map(WSC3, chr=1)
summaryMap(WSC3)
plotMap(WSC3, show.marker.names=TRUE)
plotRF(WSC3)
messedup <- switch.order(WSC3, chr=3, c(1:6,8:20,7),
                         error.prob=0.005)
plotRF(messedup, chr=3)
plotMap(messedup, show.marker.names=TRUE)
dropone <- droponemarker(WSC3, error.prob=0.02)
par(mfrow=c(2,1))
plot(dropone, lod=1, ylim=c(-100,0))
plot(dropone, lod=2, ylab="Change in chromosome length")
summary(dropone, lod.column=2)
badmar <- rownames(summary(dropone, lod.column=2))[3]
WSC3 <- drop.markers(WSC3, badmar)
newmap <- est.map(WSC3, error.prob=0.02)
WSC3 <- replace.map(WSC3, newmap)
summaryMap(WSC3)
par(mfrow=c(1,1))
plot(countXO(WSC3), ylab="Number of crossovers")
WSC3 <- subset(WSC3, ind=(countXO(WSC3) < 30))
summary(rip <- ripple(WSC3, chr=3, window=7))
summary(rip <- ripple(WSC3, chr=3, window=2, method="likelihood",
                      error.prob=0.02))
WSC3 <- switch.order(WSC3, chr=3, c(1:20), error.prob=0.005)
pull.map(WSC3, chr=3)
newmap <- est.map(WSC3, error.prob=0.02)
WSC3 <- replace.map(WSC3, newmap)
summaryMap(WSC3)
loglik <- err <- c(0.001, 0.0025, 0.005, 0.0075, 0.01, 0.0125, 0.015, 0.0175, 0.02, 0.0275, 0.035)
for(i in seq(along=err)) {
  cat(i, "of", length(err), "\n")
  tempmap <- est.map(WSC3, error.prob=err[i])
  loglik[i] <- sum(sapply(tempmap, attr, "loglik"))
}
lod <- (loglik - max(loglik))/log(10)
plot(err, lod, xlab="Genotyping error rate", xlim=c(0,0.1),
     ylab=expression(paste(log[10], " likelihood")))
WSC3 <- calc.errorlod(WSC3, error.prob=0.02)
print(toperr <- top.errorlod(WSC3, cutoff=6))
plotGeno(WSC3, chr=1, ind=toperr$id[toperr$chr==1],
         cutoff=6, include.xo=TRUE) #repeat for each chromosome
WSC3.clean <- WSC3
for(i in 1:nrow(toperr)) {
  chr <- toperr$chr[i]
  id <- toperr$id[i]
  mar <- toperr$marker[i]
  WSC3.clean$geno[[chr]]$data[WSC3$pheno$id==id, mar] <- NA
}
gt <- geno.table(WSC3, scanone.output=TRUE) #revisit segregation distortion
par(mfrow=c(2,1))
plot(gt, ylab=expression(paste(-log[10], " P-value")))
plot(gt, lod=3:5, ylab="Genotype frequency")
abline(h=c(0.25, 0.5), lty=2, col="gray")
par(mfrow=c(1,1))
plotMap(WSC3, show.marker.names=TRUE)
summary(WSC3)
#QTL analysis
plotMissing(WSC3)
plotMap(WSC3, show.marker.names=TRUE)
plotPheno(WSC3)
WSC3 <- est.rf(WSC3)
plotRF(WSC3)
WSC3 <- calc.errorlod(WSC3, error.prob=0.02)
top.errorlod(WSC3, cutoff = 6)
plotGeno(WSC3, chr=1, ind=c(7:9,27,55,59,122,162))
plotInfo(WSC3, chr=1, method="entropy")
plotInfo(WSC3, chr=1, method="variance")
WSC3 <- calc.genoprob(WSC3, step=1,error.prob=0.02) #calculates the genotype probabilities given the available marker data
par(mfrow=c(1,1))
plot.pxg(WSC3, "AOSW")
plot.pxg(WSC3, "rv0959")
plotMap(WSC3, show.marker.names=TRUE)
WSC3.out.mr <- scanone(WSC3, method = "mr")

WSC3.out.mr[WSC3.out.mr$chr==1,]
WSC3.out.mr[WSC3.out.mr$chr==2,]
WSC3.out.mr[WSC3.out.mr$chr==3,]
WSC3.out.mr[WSC3.out.mr$chr==4,]
WSC3.out.mr[WSC3.out.mr$chr==5,]
WSC3.out.mr[WSC3.out.mr$chr==6,]
WSC3.out.mr[WSC3.out.mr$chr==7,]
plot(WSC3.out.mr, chr=4, ylab="Lod score")
WSC3.out.em <- scanone(WSC3, method = "em")
WSC3.out.hk <- scanone(WSC3, method = "hk")
WSC3 <- sim.geno(WSC3, step=2, n.draws=16, error.prob=0.02)
WSC3.out.imp <- scanone(WSC3, method= "imp")
summary(WSC3.out.em)
summary(WSC3.out.hk)
summary(WSC3.out.imp)
plot(WSC3.out.em)
plot(WSC3.out.hk)
plot(WSC3.out.imp)
plot(WSC3.out.hk, col ="blue", add=TRUE)
plot(WSC3.out.imp, col="red", add=TRUE)
operm1 <- scanone(WSC3, method="hk", n.perm=100)
abline(h=3.13, lty=2, col="gray")
WSC3 <- calc.genoprob(WSC3, step = 5, error.prob=0.02)
WSC3.out2.hk <- scantwo(WSC3, method="hk")
plot(WSC3.out2.hk)
summary(WSC3.out2.hk)